/* syllabus.js — Complete 420-topic UPSC syllabus */
var SYLLABUS = [
  // ─── HISTORY (45) ───
  {id:'h1', sub:'History',icon:'🏺',col:'#FFB300',topic:'Indus Valley Civilisation',details:'Sites, features, town planning, trade, decline theories',phase:1},
  {id:'h2', sub:'History',icon:'🏺',col:'#FFB300',topic:'Vedic Age – Early & Later',details:'Rig Vedic society, Later Vedic changes, caste system formation',phase:1},
  {id:'h3', sub:'History',icon:'🏺',col:'#FFB300',topic:'Mahajanapadas & Rise of Magadha',details:'16 Mahajanapadas, Haryanka, Shishunaga, Nanda dynasties',phase:1},
  {id:'h4', sub:'History',icon:'🏺',col:'#FFB300',topic:'Jainism & Buddhism',details:'Doctrines, spread, councils, Tripitaka, Jain Agamas, differences',phase:1},
  {id:'h5', sub:'History',icon:'🏺',col:'#FFB300',topic:'Maurya Empire & Ashoka',details:'Chandragupta, Arthashastra, Ashoka Dhamma, edicts, decline',phase:1},
  {id:'h6', sub:'History',icon:'🏺',col:'#FFB300',topic:'Post-Mauryan Age',details:'Sungas, Kushanas, Satavahanas, Indo-Greeks, trade with Rome',phase:1},
  {id:'h7', sub:'History',icon:'🏺',col:'#FFB300',topic:'Gupta Empire – Golden Age',details:'Samudra Gupta, Chandragupta II, science, literature, art',phase:1},
  {id:'h8', sub:'History',icon:'🏺',col:'#FFB300',topic:'Post-Gupta & Harsha',details:'Vardhana dynasty, Harshacharita, Xuanzang visit, administration',phase:1},
  {id:'h9', sub:'History',icon:'🏺',col:'#FFB300',topic:'South India – Sangam Age',details:'Tamil Sangam literature, Pandyas, Cholas, Cheras, trade',phase:1},
  {id:'h10',sub:'History',icon:'🏺',col:'#FFB300',topic:'Pallavas, Chalukyas, Rashtrakutas',details:'Temple architecture, political history, cultural contributions',phase:1},
  {id:'h11',sub:'History',icon:'🏺',col:'#FFB300',topic:'Rajput Age & Arab Invasion',details:'Pratiharas, Paramaras, Muhammad bin Qasim, Battle of Tarain',phase:1},
  {id:'h12',sub:'History',icon:'🏺',col:'#FFB300',topic:'Delhi Sultanate – Slave Dynasty',details:'Qutb-ud-din Aibak, Iltutmish, Razia Sultana, Balban',phase:1},
  {id:'h13',sub:'History',icon:'🏺',col:'#FFB300',topic:'Delhi Sultanate – Khilji & Tughlaq',details:'Alauddin market reforms, Muhammad Tughlaq experiments, Firuz Tughlaq',phase:1},
  {id:'h14',sub:'History',icon:'🏺',col:'#FFB300',topic:'Vijayanagara Empire',details:'Krishna Deva Raya, Amuktamalyada, administration, Hampi',phase:1},
  {id:'h15',sub:'History',icon:'🏺',col:'#FFB300',topic:'Bhakti & Sufi Movements',details:'Kabir, Mirabai, Chaitanya, Tukaram, Sufi orders, impact',phase:1},
  {id:'h16',sub:'History',icon:'🏺',col:'#FFB300',topic:'Mughal Empire – Babur to Akbar',details:'Panipat battles, Akbar administration, Din-i-Ilahi, Mansabdari',phase:1},
  {id:'h17',sub:'History',icon:'🏺',col:'#FFB300',topic:'Mughal Empire – Jahangir to Aurangzeb',details:'Nur Jahan, Shah Jahan architecture, Aurangzeb policy, decline',phase:1},
  {id:'h18',sub:'History',icon:'🏺',col:'#FFB300',topic:'Maratha Empire',details:'Shivaji, Ashtapradhan, Peshwas, Battle of Panipat III',phase:1},
  {id:'h19',sub:'History',icon:'🏺',col:'#FFB300',topic:'European Arrival in India',details:'Portuguese, Dutch, French, British East India Company arrival',phase:1},
  {id:'h20',sub:'History',icon:'🏺',col:'#FFB300',topic:'British Expansion – Wars & Policies',details:'Plassey, Buxar, subsidiary alliance, doctrine of lapse',phase:1},
  {id:'h21',sub:'History',icon:'🏺',col:'#FFB300',topic:'1857 – First War of Independence',details:'Causes, centres, leaders, Bahadur Shah Zafar, impact',phase:1},
  {id:'h22',sub:'History',icon:'🏺',col:'#FFB300',topic:'British Economic Impact on India',details:'Deindustrialisation, drain of wealth, land revenue systems',phase:1},
  {id:'h23',sub:'History',icon:'🏺',col:'#FFB300',topic:'Social & Religious Reform Movements',details:'Raja Ram Mohan Roy, Brahmo Samaj, Arya Samaj, Prarthana',phase:1},
  {id:'h24',sub:'History',icon:'🏺',col:'#FFB300',topic:'INC Formation & Moderate Phase',details:'A.O. Hume 1885, Bombay, moderate demands, methods',phase:2},
  {id:'h25',sub:'History',icon:'🏺',col:'#FFB300',topic:'Partition of Bengal & Swadeshi',details:'Curzon 1905, Swadeshi movement, Extremists vs Moderates',phase:2},
  {id:'h26',sub:'History',icon:'🏺',col:'#FFB300',topic:'Home Rule & Lucknow Pact',details:'Tilak, Annie Besant, 1916 Lucknow Pact Congress-Muslim League',phase:2},
  {id:'h27',sub:'History',icon:'🏺',col:'#FFB300',topic:'Gandhi – Early Satyagrahas',details:'Champaran, Kheda, Ahmedabad, Rowlatt Act, Jallianwala Bagh',phase:2},
  {id:'h28',sub:'History',icon:'🏺',col:'#FFB300',topic:'Non-Cooperation Movement 1920-22',details:'Programme, Chauri Chaura Feb 1922, suspension, impact',phase:2},
  {id:'h29',sub:'History',icon:'🏺',col:'#FFB300',topic:'Simon Commission & Nehru Report',details:'1927 boycott, 1928 Nehru Report, Jinnah 14 points',phase:2},
  {id:'h30',sub:'History',icon:'🏺',col:'#FFB300',topic:'Civil Disobedience Movement 1930',details:'Dandi March, Round Table Conferences, Gandhi-Irwin Pact',phase:2},
  {id:'h31',sub:'History',icon:'🏺',col:'#FFB300',topic:'Government of India Act 1935',details:'Provincial autonomy, Federation of India, dyarchy at Centre',phase:2},
  {id:'h32',sub:'History',icon:'🏺',col:'#FFB300',topic:'Quit India Movement 1942',details:'Do or Die, August Kranti, underground leaders, Aruna Asaf Ali',phase:2},
  {id:'h33',sub:'History',icon:'🏺',col:'#FFB300',topic:'INA & Subhas Chandra Bose',details:'Azad Hind Fauj, Singapore, INA trials, impact on independence',phase:2},
  {id:'h34',sub:'History',icon:'🏺',col:'#FFB300',topic:'Partition & Independence 1947',details:'Cabinet Mission, Direct Action Day, Mountbatten Plan, radcliffe',phase:2},
  // Art & Culture
  {id:'h35',sub:'History',icon:'🎨',col:'#FFB300',topic:'Ancient Architecture – Temples & Caves',details:'Nagara, Dravida, Vesara styles; rock-cut caves; Ajanta, Ellora',phase:1},
  {id:'h36',sub:'History',icon:'🎨',col:'#FFB300',topic:'Medieval & Mughal Architecture',details:'Qutb Minar, Taj Mahal, Red Fort, Mughal gardens, Indo-Islamic',phase:1},
  {id:'h37',sub:'History',icon:'🎨',col:'#FFB300',topic:'Sculpture & Painting Traditions',details:'Gandhara, Mathura; Ajanta frescoes, Mughal miniature, Kangra',phase:1},
  {id:'h38',sub:'History',icon:'🎨',col:'#FFB300',topic:'Classical Dance & Music Forms',details:'Bharatnatyam, Kathak, Odissi; Hindustani vs Carnatic music',phase:1},
  {id:'h39',sub:'History',icon:'🎨',col:'#FFB300',topic:'Indian Literature – Sanskrit to Regional',details:'Vedas, Upanishads, epics; Sangam; Kabir, Tulsidas, Mirabai',phase:1},
  {id:'h40',sub:'History',icon:'🎨',col:'#FFB300',topic:'Fairs, Festivals & Folk Traditions',details:'Major festivals, folk arts, tribal culture, craft traditions',phase:1},
  // World History
  {id:'h41',sub:'History',icon:'🌍',col:'#FFB300',topic:'Enlightenment & Revolutions',details:'French Revolution, American Independence, Enlightenment thinkers',phase:2},
  {id:'h42',sub:'History',icon:'🌍',col:'#FFB300',topic:'Imperialism & World Wars',details:'Industrial revolution, colonialism, WWI causes, WWII causes & effects',phase:2},
  {id:'h43',sub:'History',icon:'🌍',col:'#FFB300',topic:'Post-WWII World Order',details:'Cold War, UN, decolonisation, Non-Aligned Movement, nuclear age',phase:2},
  {id:'h44',sub:'History',icon:'🌍',col:'#FFB300',topic:'Post-Independence India Consolidation',details:'Integration of princely states, Sardar Patel, reorganisation of states',phase:3},
  {id:'h45',sub:'History',icon:'🌍',col:'#FFB300',topic:'India Since Independence – Major Events',details:'Emergency 1975, Green Revolution, economic reforms 1991',phase:3},

  // ─── POLITY (30) ───
  {id:'p1', sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Historical Background of Constitution',details:'Regulating Act 1773, Pitt India Act, 1858 Act, Government of India Acts',phase:1},
  {id:'p2', sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Making of the Constitution',details:'Constituent Assembly, committees, B.R. Ambedkar, sources, features',phase:1},
  {id:'p3', sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Preamble & Salient Features',details:'Sovereign Socialist Secular Democratic Republic; key features',phase:1},
  {id:'p4', sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Union & Citizenship',details:'Art 1-4 Union of India; Art 5-11 citizenship, Citizenship Act 1955',phase:1},
  {id:'p5', sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Fundamental Rights – Art 12-35',details:'6 FR categories, restrictions, writs, judicial review, doctrines',phase:1},
  {id:'p6', sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'DPSPs & Fundamental Duties',details:'Art 36-51 DPSPs (3 types); Art 51A FDs (42nd & 86th Amendments)',phase:1},
  {id:'p7', sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Amendment of Constitution – Art 368',details:'3 methods, Basic Structure doctrine, Kesavananda Bharati 1973',phase:1},
  {id:'p8', sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Parliament – Lok Sabha & Rajya Sabha',details:'Composition, powers, sessions, speaker, joint sitting, differences',phase:2},
  {id:'p9', sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Parliamentary Procedures & Bills',details:'Questions, motions, Money Bill, Financial Bill, CAG, budget',phase:2},
  {id:'p10',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'President & Vice President',details:'Election, powers, emergency, Art 52-78; VP as RS Chairman',phase:2},
  {id:'p11',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'PM & Council of Ministers',details:'Art 74-78, collective responsibility, PM powers, cabinet system',phase:2},
  {id:'p12',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Supreme Court',details:'Composition, original/appellate/advisory/writ jurisdiction, PIL',phase:2},
  {id:'p13',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'High Courts & Subordinate Courts',details:'Jurisdiction, judicial review, transfer, tribunals Art 323A/B',phase:2},
  {id:'p14',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'State Government',details:'Governor, CM, State Legislature Art 152-237, state-centre relations',phase:2},
  {id:'p15',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Centre-State Relations',details:'Legislative Art 245-255, Administrative Art 256-263, Financial',phase:2},
  {id:'p16',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Emergency Provisions',details:'National Art 352, State Art 356, Financial Art 360, safeguards',phase:2},
  {id:'p17',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Constitutional Bodies',details:'CAG Art 148, UPSC Art 315, EC Art 324 – powers, composition',phase:2},
  {id:'p18',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Statutory Bodies',details:'CBI, CVC, CIC, Lokpal, NHRC – legal basis, jurisdiction',phase:2},
  {id:'p19',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Panchayati Raj – 73rd Amendment',details:'Part IX, 11th Schedule, 3-tier, reservation, elections, PESA',phase:2},
  {id:'p20',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Urban Local Bodies – 74th Amendment',details:'Part IXA, 12th Schedule, types of ULBs, ward committees',phase:2},
  {id:'p21',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Federalism in India',details:'Federal features, unitary bias, cooperative federalism, GST Council',phase:2},
  {id:'p22',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Secularism in India',details:'Indian vs Western model, Art 25-28, state neutrality, controversies',phase:2},
  {id:'p23',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Representation of People Act',details:'Qualifications, disqualification, EVM, VVPAT, election process',phase:3},
  {id:'p24',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'RTI Act 2005',details:'Provisions, exemptions Art 8, CIC/SIC, 2019 amendment controversy',phase:3},
  {id:'p25',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Special Constitutional Provisions',details:'Art 370 (abrogated 2019), J&K, NE states Art 371, 5th & 6th Schedule',phase:2},
  {id:'p26',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Finance Commission & NITI Aayog',details:'Art 280, Finance Commission role, NITI Aayog vs Planning Commission',phase:2},
  {id:'p27',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Attorney General & Solicitor General',details:'Art 76, AG powers, role, difference from Advocate General',phase:2},
  {id:'p28',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Important Constitutional Amendments',details:'1st, 7th, 24th, 42nd, 44th, 61st, 73rd, 74th, 86th, 101st, 103rd, 104th',phase:3},
  {id:'p29',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Judiciary – Landmark Cases',details:'Golaknath, Kesavananda, Maneka Gandhi, Indra Sawhney, Bommai',phase:3},
  {id:'p30',sub:'Polity',icon:'⚖️',col:'#FF6B00',topic:'Anti-Defection Law – 10th Schedule',details:'52nd Amendment 1985, grounds, Speaker role, recent controversies',phase:3},

  // ─── GEOGRAPHY (27) ───
  {id:'g1', sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Origin of Earth & Geomorphic Processes',details:'Big Bang, solar system, interior, plate tectonics, endogenic/exogenic',phase:1},
  {id:'g2', sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Landforms – Fluvial, Glacial, Wind, Coastal',details:'River, glacial, desert, coastal landforms and their formation',phase:1},
  {id:'g3', sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Climate – Atmosphere, Insolation, Pressure',details:'Atmospheric layers, heating, pressure belts, wind systems, jet streams',phase:1},
  {id:'g4', sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Precipitation & Ocean Currents',details:'Types of rainfall, El Nino/La Nina, ENSO, warm/cold currents',phase:1},
  {id:'g5', sub:'Geography',icon:'🗺️',col:'#52B788',topic:'World Biomes & World Geography',details:'Tropical/temperate/boreal forests, deserts, tundra; important countries',phase:1},
  {id:'g6', sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India Physiography – 5 Divisions',details:'Himalayas, Northern Plains, Peninsular Plateau, Coastal Plains, Islands',phase:1},
  {id:'g7', sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – The Himalayas & Mountain Passes',details:'3 ranges, Karakoram, Ladakh, passes (Zoji La, Nathu La, Shipki La)',phase:1},
  {id:'g8', sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – Northern Plains & Zones',details:'Formation, Bhabar, Terai, Bhangar, Khadar zones, significance',phase:1},
  {id:'g9', sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – Peninsular Plateau & Ghats',details:'Deccan, Central Highlands, Eastern vs Western Ghats comparison',phase:1},
  {id:'g10',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – Drainage System & Rivers',details:'Himalayan rivers (Indus/Ganga/Brahmaputra) vs Peninsular rivers',phase:1},
  {id:'g11',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – Monsoon & Climate',details:'SW & NE monsoon, onset/retreat, El Nino, La Nina, climatic regions',phase:1},
  {id:'g12',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – Soils (8 types)',details:'Alluvial, Black, Red, Laterite, Arid, Saline, Peaty, Forest soils',phase:1},
  {id:'g13',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – Natural Vegetation & Wildlife',details:'Tropical wet, deciduous, thorny, montane; NPs, sanctuaries, biosphere',phase:1},
  {id:'g14',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – Agriculture & Irrigation',details:'Kharif/Rabi crops, Green Revolution, APMCs, irrigation systems',phase:2},
  {id:'g15',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – Minerals & Energy Resources',details:'Coal, iron ore, mica, petroleum, natural gas; producing states',phase:2},
  {id:'g16',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – Industries & Locations',details:'Iron & Steel, Textile, Chemical, Cement; SEZs, industrial corridors',phase:2},
  {id:'g17',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – Transport & Communication',details:'Railways, road network (NH), waterways (NW1-NW3), airports, pipelines',phase:2},
  {id:'g18',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India – Population & Census 2011',details:'Density, sex ratio, literacy, urbanisation, population policy',phase:2},
  {id:'g19',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Coastal Plains & Islands',details:'Western vs Eastern coasts; A&N Islands (volcanic); Lakshadweep (coral)',phase:1},
  {id:'g20',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Important Water Bodies & Straits',details:'Palk Strait, Malacca, Hormuz, Mandeb, Suez, Panama; Indian Ocean',phase:2},
  {id:'g21',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Mapping Skills – India & World',details:'River, mountain, dam, NP, city locations on blank maps',phase:3},
  {id:'g22',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Urban Geography & Smart Cities',details:'Urbanisation trends, metro cities, smart cities mission, slums',phase:3},
  {id:'g23',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Glaciers & Himalayan Ecosystem',details:'Gangotri, Siachen, glacial retreat, Himalayan rivers water security',phase:2},
  {id:'g24',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'India Neighbours – Strategic Geography',details:'Borders with 7 countries, LOC, LAC, maritime boundaries, EEZ',phase:2},
  {id:'g25',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Natural Disasters – Cyclones & Earthquakes',details:'Cyclone belts, seismic zones, India vulnerabilities, NDMA',phase:2},
  {id:'g26',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Water Resources & Interlinking',details:'River interlinking project, Ken-Betwa, groundwater depletion',phase:3},
  {id:'g27',sub:'Geography',icon:'🗺️',col:'#52B788',topic:'Economic Geography – Trade Routes',details:'Chabahar, Vladivostok, BRI, INSTC, ancient Silk Road',phase:3},

  // ─── ECONOMY (25) ───
  {id:'e1', sub:'Economy',icon:'💰',col:'#2176FF',topic:'National Income Concepts',details:'GDP, GNP, NNP, National Income, Per Capita; measurement methods',phase:1},
  {id:'e2', sub:'Economy',icon:'💰',col:'#2176FF',topic:'Indian Economy & Planning',details:'Mixed economy, Planning Commission, NITI Aayog, 5-year plans',phase:1},
  {id:'e3', sub:'Economy',icon:'💰',col:'#2176FF',topic:'Agriculture Policy & Land Reforms',details:'Land ceiling, tenancy reform, agrarian distress, farm laws',phase:1},
  {id:'e4', sub:'Economy',icon:'💰',col:'#2176FF',topic:'Agriculture Marketing & MSP',details:'APMCs, e-NAM, MSP mechanism, PDS, Food Corporation of India',phase:1},
  {id:'e5', sub:'Economy',icon:'💰',col:'#2176FF',topic:'Industrial Policy & LPG Reforms 1991',details:'Industrial licensing, FEMA, FERA, Make in India, PLI schemes',phase:1},
  {id:'e6', sub:'Economy',icon:'💰',col:'#2176FF',topic:'MSMEs & Manufacturing',details:'MSME definition, role in employment & exports, challenges, schemes',phase:1},
  {id:'e7', sub:'Economy',icon:'💰',col:'#2176FF',topic:'Money Supply & Monetary Policy',details:'M0-M3, RBI functions, repo, reverse repo, CRR, SLR, OMO',phase:2},
  {id:'e8', sub:'Economy',icon:'💰',col:'#2176FF',topic:'Inflation – Types & Control',details:'CPI, WPI, core inflation, demand-pull, cost-push, remedies',phase:2},
  {id:'e9', sub:'Economy',icon:'💰',col:'#2176FF',topic:'Banking System & NBFCs',details:'Commercial banks, cooperative banks, NBFCs, payment banks, SFBs',phase:2},
  {id:'e10',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Financial Inclusion & Digital Payments',details:'Jan Dhan, UPI, BHIM, PM-JJB, PMSBY, RuPay, DigiLocker',phase:2},
  {id:'e11',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Capital Markets & SEBI',details:'Primary/secondary markets, SEBI powers, IPO, bonds, derivatives',phase:2},
  {id:'e12',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Union Budget – Structure & Deficits',details:'Revenue vs Capital, deficit types, FRBM Act 2003, fiscal consolidation',phase:2},
  {id:'e13',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Taxation – Direct & Indirect',details:'Income tax, corporate tax, GST (CGST/SGST/IGST), customs, excise',phase:2},
  {id:'e14',sub:'Economy',icon:'💰',col:'#2176FF',topic:'External Sector – Trade & BoP',details:'Balance of Trade, Current Account, BoP, trade policy, WTO issues',phase:2},
  {id:'e15',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Foreign Investment – FDI & FII',details:'Automatic route, approval route, sector caps, FPI, sovereign funds',phase:2},
  {id:'e16',sub:'Economy',icon:'💰',col:'#2176FF',topic:'International Economic Organisations',details:'WTO, IMF, World Bank, ADB, AIIB, BRICS NDB, G20, G7',phase:2},
  {id:'e17',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Infrastructure – Energy & Transport',details:'Coal, petroleum, nuclear, renewable; roads, railways, logistics',phase:2},
  {id:'e18',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Poverty & Inequality Measures',details:'Poverty lines, Tendulkar/Rangarajan committees, Gini coefficient',phase:3},
  {id:'e19',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Unemployment & Labour Reforms',details:'Types of unemployment, MGNREGS, Labour Codes 2020, gig economy',phase:3},
  {id:'e20',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Key Government Economic Schemes',details:'PM Kisan, PMGSY, Startup India, Skill India, Mudra, PMAY',phase:3},
  {id:'e21',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Economic Survey & Key Indicators',details:'GDP growth, fiscal deficit, CAD, forex reserves, inflation data',phase:3},
  {id:'e22',sub:'Economy',icon:'💰',col:'#2176FF',topic:'India Stack & Digital Economy',details:'Aadhaar, UPI, DigiLocker, Account Aggregator, ONDC, Open Networks',phase:3},
  {id:'e23',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Food Security & NFSA 2013',details:'National Food Security Act, PDS reform, Antyodaya Anna Yojana',phase:2},
  {id:'e24',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Competition Policy & CCI',details:'Competition Commission of India, anti-competitive practices, M&A',phase:3},
  {id:'e25',sub:'Economy',icon:'💰',col:'#2176FF',topic:'Disinvestment & Public Sector',details:'Privatisation policy, strategic disinvestment, NITI Aayog role',phase:3},

  // ─── ENVIRONMENT (23) ───
  {id:'ev1', sub:'Environment',icon:'🌿',col:'#40916C',topic:'Ecology – Basic Concepts',details:'Ecosystem, biotic/abiotic, food chain, energy flow, 10% law',phase:1},
  {id:'ev2', sub:'Environment',icon:'🌿',col:'#40916C',topic:'Ecological Pyramids & Nutrient Cycles',details:'Number/biomass/energy pyramids; N, C, P, S, water cycles',phase:1},
  {id:'ev3', sub:'Environment',icon:'🌿',col:'#40916C',topic:'Biodiversity – Levels, Types, Hotspots',details:'Genetic/species/ecosystem diversity; 34 global hotspots; India 4',phase:1},
  {id:'ev4', sub:'Environment',icon:'🌿',col:'#40916C',topic:'Conservation – In-situ & Ex-situ',details:'NPs, WLSs, biosphere reserves (18 in India), zoos, gene banks',phase:1},
  {id:'ev5', sub:'Environment',icon:'🌿',col:'#40916C',topic:'Wildlife Laws & Forest Policy',details:'WPA 1972 (schedules), FCA 1980, NFP 1988, CAMPA, community forests',phase:1},
  {id:'ev6', sub:'Environment',icon:'🌿',col:'#40916C',topic:'National Parks & Tiger Reserves',details:'Jim Corbett, Kaziranga, Gir, Sundarbans; 53 tiger reserves facts',phase:1},
  {id:'ev7', sub:'Environment',icon:'🌿',col:'#40916C',topic:'Wetlands – Types & Ramsar Sites',details:'Ramsar 1971, India 75+ sites, Chilika (1981), Sambhar; mangroves',phase:1},
  {id:'ev8', sub:'Environment',icon:'🌿',col:'#40916C',topic:'Air Pollution – Sources & AQI',details:'Pollutants (PM2.5, NOx, SOx), AQI, NAAQS, CPCB, health impacts',phase:2},
  {id:'ev9', sub:'Environment',icon:'🌿',col:'#40916C',topic:'Water & Soil Pollution',details:'River pollution, Ganga clean-up, soil degradation, SWM Rules 2016',phase:2},
  {id:'ev10',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Climate Change – Causes & Impacts',details:'GHGs, IPCC reports, global warming effects, tipping points',phase:2},
  {id:'ev11',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Ozone Layer & Montreal Protocol',details:'CFCs, ozone hole, Montreal Protocol 1987, Kigali Amendment',phase:2},
  {id:'ev12',sub:'Environment',icon:'🌿',col:'#40916C',topic:'UNFCCC, Paris Agreement & COPs',details:'COP history, NDCs, 1.5°C goal, loss & damage fund, India NDCs',phase:2},
  {id:'ev13',sub:'Environment',icon:'🌿',col:'#40916C',topic:'International Environmental Conventions',details:'CITES, CBD, Basel, Ramsar, Nagoya Protocol, Cartagena Protocol',phase:2},
  {id:'ev14',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Renewable Energy in India',details:'Solar, wind, hydro targets; IRENA; PM-KUSUM; offshore wind',phase:2},
  {id:'ev15',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Disaster Management',details:'NDMA, NDRF, Sendai Framework 2015-30, NDMP, disaster types',phase:2},
  {id:'ev16',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Environmental Laws – EPA & EIA',details:'Environment Protection Act 1986, EIA notification, NGT powers',phase:2},
  {id:'ev17',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Marine & Ocean Pollution',details:'Plastic in oceans, MARPOL, deep sea mining, coral bleaching',phase:3},
  {id:'ev18',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Green Hydrogen & Energy Transition',details:'National Green Hydrogen Mission, 5 MT by 2030, electrolysers',phase:3},
  {id:'ev19',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Desertification & Land Degradation',details:'UNCCD, land degradation neutrality, India dryland areas',phase:3},
  {id:'ev20',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Environmental Schemes & Missions',details:'CAMPA, AMRUT, Smart Cities, Jal Jeevan Mission, FAME-II',phase:3},
  {id:'ev21',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Coral Reefs & Marine Biodiversity',details:'Coral bleaching, Great Barrier Reef, Gulf of Mannar, Lakshadweep',phase:2},
  {id:'ev22',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Invasive Species & Threats to Biodiversity',details:'Parthenium, water hyacinth, lantana; habitat loss, poaching',phase:2},
  {id:'ev23',sub:'Environment',icon:'🌿',col:'#40916C',topic:'Biosphere Reserves & UNESCO Sites',details:'18 Indian BRs; UNESCO WH natural sites in India; MAB programme',phase:2},

  // ─── SCIENCE & TECH (15) ───
  {id:'s1', sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Space Technology – ISRO Missions',details:'Chandrayaan 1/2/3, Mangalyaan, Aditya-L1, XPoSat, Gaganyaan',phase:2},
  {id:'s2', sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Satellites & Applications',details:'IRNSS/NavIC, RISAT, GSAT, remote sensing, GPS, OneWeb',phase:2},
  {id:'s3', sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Nuclear Technology & Policy',details:'Fission/fusion, India nuclear programme, NPT, CTBT, NSG waiver',phase:2},
  {id:'s4', sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Defence Technology',details:'Agni/Prithvi missiles, BrahMos, DRDO, Tejas LCA, INS Vikrant',phase:2},
  {id:'s5', sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Biotechnology – CRISPR & Applications',details:'DNA recombination, CRISPR-Cas9, GM crops, Bt cotton, biofuels',phase:2},
  {id:'s6', sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Health Technology & Vaccines',details:'mRNA vaccines, COVAXIN, telemedicine, Ayushman Bharat PM-JAY',phase:2},
  {id:'s7', sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Information Technology & e-Governance',details:'e-Kranti, DigiLocker, UMANG, CSC, UIDAI, India Stack',phase:2},
  {id:'s8', sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Artificial Intelligence & Machine Learning',details:'AI policy, NITI AI strategy, IndiaAI Mission (Rs 10,371cr), risks',phase:2},
  {id:'s9', sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Cyber Security & IT Act',details:'Cyberattacks, CERT-In, IT Act 2000, DPDP Act 2023, cyber sovereignty',phase:2},
  {id:'s10',sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Nanotechnology & Quantum Computing',details:'Nano applications; NM-QTA Rs 8000cr; quantum encryption, computing',phase:2},
  {id:'s11',sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'5G Technology & Semiconductors',details:'5G spectrum, India rollout; India Semiconductor Mission, Tata/Micron',phase:3},
  {id:'s12',sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Robotics, Drones & Automation',details:'Drone Policy 2021, drone corridors, industrial robots, autonomous systems',phase:3},
  {id:'s13',sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Genome India & Bioeconomy',details:'Genome sequencing project, biobank, personalised medicine, bioinformatics',phase:3},
  {id:'s14',sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Green Technology – EV & Hydrogen',details:'FAME-II, EV adoption, charging infra, National Green Hydrogen Mission',phase:3},
  {id:'s15',sub:'Science',icon:'🔬',col:'#7B2FBE',topic:'Science in Everyday Life – UPSC Basics',details:'Basic physics (nuclear, sound, light), chemistry (elements, reactions)',phase:1},

  // ─── GOVERNANCE & SOCIAL JUSTICE (15) ───
  {id:'gs1', sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Civil Services – Role & ARC Reports',details:'IAS/IPS/IFS; ARC recommendations; lateral entry; performance mgmt',phase:2},
  {id:'gs2', sub:'Governance',icon:'🏛️',col:'#E63946',topic:'E-Governance & Digital Delivery',details:'NeGP, e-Kranti, MeeSeva, DigiLocker, UMANG, Common Service Centres',phase:2},
  {id:'gs3', sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Transparency & Accountability',details:'RTI, Lokpal, CVC, whistleblower protection, Social audit',phase:2},
  {id:'gs4', sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Social Justice – Reservation Policy',details:'Constitutional basis, SC/ST/OBC reservations, Mandal, Indra Sawhney',phase:2},
  {id:'gs5', sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Women Empowerment & Gender',details:'Legal protections, schemes (Beti Bachao), gender budgeting, SHGs',phase:2},
  {id:'gs6', sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Education Policy – NEP 2020',details:'5+3+3+4 structure, CUET, mother tongue, vocational, higher ed reforms',phase:2},
  {id:'gs7', sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Health Policy & Nutrition',details:'NHM, PMJAY, Ayushman Bharat, POSHAN Mission, mental health',phase:2},
  {id:'gs8', sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Poverty Alleviation Schemes',details:'MGNREGS, PMAY-G&U, PMGSY, food security, NFSA 2013',phase:2},
  {id:'gs9', sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Vulnerable Groups Protection',details:'POCSO, ICPS, National Policy for Senior Citizens, RPWD Act 2016',phase:2},
  {id:'gs10',sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Internal Security Overview',details:'Terrorism, naxalism, communalism, insurgency NE, cyber threats',phase:3},
  {id:'gs11',sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Left Wing Extremism – Naxalism',details:'History, red corridor, SAMADHAN policy, development approach',phase:3},
  {id:'gs12',sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Border & Coastal Security',details:'Border guarding forces (BSF, SSB, ITBP), coastal security post-26/11',phase:3},
  {id:'gs13',sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Security Agencies & Laws',details:'NIA, NSG, RAW, IB, UAPA 2019, Armed Forces Special Powers Act',phase:3},
  {id:'gs14',sub:'Governance',icon:'🏛️',col:'#E63946',topic:'NGOs, SHGs & Civil Society',details:'Role in governance, NABARD SHG-bank linkage, FCRA regulation',phase:2},
  {id:'gs15',sub:'Governance',icon:'🏛️',col:'#E63946',topic:'Tribal Issues & Forest Rights',details:'FRA 2006, tribal autonomy, PESA 1996, 5th/6th Schedule areas',phase:2},

  // ─── IR (10) ───
  {id:'ir1', sub:'IR',icon:'🌐',col:'#F4A261',topic:'India Foreign Policy – Basics & Panchsheel',details:'Determinants, Panchsheel 1954, NAM, strategic autonomy evolution',phase:2},
  {id:'ir2', sub:'IR',icon:'🌐',col:'#F4A261',topic:'Neighbourhood First – SAARC Countries',details:'Pakistan, Bangladesh, Nepal, Bhutan, Sri Lanka, Maldives, Myanmar',phase:2},
  {id:'ir3', sub:'IR',icon:'🌐',col:'#F4A261',topic:'India-China Relations',details:'Border dispute, LAC, 1962 war, Doklam, Galwan 2020, trade ties',phase:2},
  {id:'ir4', sub:'IR',icon:'🌐',col:'#F4A261',topic:'India-USA & India-Russia Relations',details:'QUAD, defence deals, S-400, CAATSA waiver, Ukraine war impact',phase:2},
  {id:'ir5', sub:'IR',icon:'🌐',col:'#F4A261',topic:'Act East Policy – ASEAN & Indo-Pacific',details:'Look East to Act East, ASEAN FTA, Indo-Pacific Ocean Initiative',phase:2},
  {id:'ir6', sub:'IR',icon:'🌐',col:'#F4A261',topic:'India-Middle East & Africa',details:'Remittances, energy security, I2U2, UAE-India CEPA, African Union',phase:2},
  {id:'ir7', sub:'IR',icon:'🌐',col:'#F4A261',topic:'United Nations & India',details:'UNSC permanent seat bid, peacekeeping, UN agencies, reform',phase:2},
  {id:'ir8', sub:'IR',icon:'🌐',col:'#F4A261',topic:'International Organisations',details:'IMF, World Bank, WTO, G20 India presidency, BRICS, SCO, Commonwealth',phase:2},
  {id:'ir9', sub:'IR',icon:'🌐',col:'#F4A261',topic:'Diaspora & Soft Power',details:'Indian diaspora 32 million+, OCI, Pravasi Bharatiya, Yoga Day, culture',phase:3},
  {id:'ir10',sub:'IR',icon:'🌐',col:'#F4A261',topic:'Connectivity & Infrastructure Projects',details:'Chabahar, INSTC, BRI counter, Sagarmala, IMEC, blue economy',phase:3},

  // ─── ETHICS (13) ───
  {id:'et1', sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Nature & Sources of Ethics',details:'Definition, scope, meta-ethics, normative, applied; moral philosophy',phase:2},
  {id:'et2', sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Ethical Theories – Consequentialism',details:'Utilitarianism: Bentham, J.S. Mill; hedonistic calculus, act vs rule',phase:2},
  {id:'et3', sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Ethical Theories – Deontology',details:'Kant Categorical Imperative; duty-based; rights theory',phase:2},
  {id:'et4', sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Virtue Ethics & Care Ethics',details:'Aristotle eudaimonia; virtues; Carol Gilligan care ethics',phase:2},
  {id:'et5', sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Indian Ethical Traditions',details:'Dharma, Ahimsa; Gandhi, Ambedkar, Vivekananda, Chanakya',phase:2},
  {id:'et6', sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Attitude – Formation & Change',details:'Components (CAB), cognitive dissonance, prejudice, persuasion',phase:2},
  {id:'et7', sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Emotional Intelligence – Goleman',details:'5 components: self-awareness, regulation, motivation, empathy, social',phase:2},
  {id:'et8', sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Civil Service Values & Code of Conduct',details:'Integrity, impartiality, objectivity, non-partisanship, accountability',phase:2},
  {id:'et9', sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Public Sector Ethics & Corruption',details:'Conflict of interest, nepotism, whistleblowing, corporate governance',phase:3},
  {id:'et10',sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Moral Thinkers – East & West',details:'Aristotle, Kant, Rawls; Gandhi, Ambedkar, Chanakya, Socrates, Plato',phase:2},
  {id:'et11',sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Probity in Governance',details:'Philosophical basis, RTI, citizen charter, work culture, service delivery',phase:3},
  {id:'et12',sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Case Studies – Methodology & Practice',details:'IDEAL approach; identify dilemma, stakeholders, evaluate, act, learn',phase:3},
  {id:'et13',sub:'Ethics',icon:'🧠',col:'#FF6B6B',topic:'Case Studies – 5 Practice Scenarios',details:'Bribery, whistleblowing, resource allocation, disaster response, conflict',phase:3},

  // ─── CSAT (10) ───
  {id:'cs1', sub:'CSAT',icon:'📝',col:'#9B5DE5',topic:'Reading Comprehension – Strategy & Practice',details:'Skimming, scanning, inference, tone, 20 practice passages',phase:2},
  {id:'cs2', sub:'CSAT',icon:'📝',col:'#9B5DE5',topic:'Logical Reasoning – Basics',details:'Statements & conclusions, assumptions, inferences, paradox, CR',phase:2},
  {id:'cs3', sub:'CSAT',icon:'📝',col:'#9B5DE5',topic:'Logical Reasoning – Advanced',details:'Syllogisms, blood relations, direction sense, coding-decoding',phase:2},
  {id:'cs4', sub:'CSAT',icon:'📝',col:'#9B5DE5',topic:'Data Interpretation – Charts & Tables',details:'Bar, pie, line charts; DI tricks; approximation technique',phase:2},
  {id:'cs5', sub:'CSAT',icon:'📝',col:'#9B5DE5',topic:'Basic Numeracy – Number System',details:'HCF/LCM, fractions, decimals, surds, simplification tricks',phase:2},
  {id:'cs6', sub:'CSAT',icon:'📝',col:'#9B5DE5',topic:'Basic Numeracy – Arithmetic',details:'Percentage, ratio, profit/loss, time-speed-distance, average',phase:2},
  {id:'cs7', sub:'CSAT',icon:'📝',col:'#9B5DE5',topic:'Answer Writing – Structure & Format',details:'Intro-Body-Conclusion, headings, word limits, directive words',phase:3},
  {id:'cs8', sub:'CSAT',icon:'📝',col:'#9B5DE5',topic:'Essay Writing – Strategy & Topics',details:'Essay paper, introduction types, arguments, conclusion, practice',phase:3},
  {id:'cs9', sub:'CSAT',icon:'📝',col:'#9B5DE5',topic:'CSAT Full Mock Tests',details:'3 full mock tests (80Q each) with analysis and scoring',phase:3},
  {id:'cs10',sub:'CSAT',icon:'📝',col:'#9B5DE5',topic:'Decision Making & Problem Solving',details:'Situation-based questions, administrative decisions, CSAT Paper 2',phase:2},
];
